package database;

import java.util.Date;

/**
 * Represents one mission and its associated information
 * @author Marco Olivieri on 26/11/2017 (Team 3)
 */

public class Mission {

    private int ID;
    private Date startMission;
    private Date endMission;
    private String locality;
    private boolean isRepay;

    /**
     * Non parametric constructor
     */
    public Mission() {
    }

    /**
     * Parametric constructor
     *
     * @param ID Unique ID of the Mission
     * @param startMission Date of the beginning of the mission
     * @param endMission Date of the end of the mission
     * @param locality Name of locality where the mission took place
     */
    public Mission(int ID, Date startMission, Date endMission, String locality) {
        this.ID = ID;
        this.startMission = startMission;
        this.endMission = endMission;
        this.locality = locality;
        isRepay = false;
    }

    /**
     * Returns the mission ID
     * @return  ID
     */
    public int getID() {
        return ID;
    }

    @Deprecated
    /** This method should no longer exists, since the ID is auto-generated by the database
     * Set mission id
     * @param ID not null
     */
    public void setID(int ID) {
        this.ID = ID;
    }

    /**
     * Returns the beginning date of the mission
     * @return startMission
     */
    public Date getStartMission() {
        return startMission;
    }

    /**
     * Sets the beginning date of the mission
     * @param startMission
     */
    public void setStartMission(Date startMission) {
        this.startMission = startMission;
    }

    /**
     * Returns the end date of the mission
     * @return endMission
     */
    public Date getEndMission() {
        return endMission;
    }

    /**
     * Sets the end date of the mission
     * @param endMission
     */
    public void setEndMission(Date endMission) {
        this.endMission = endMission;
    }

    /**
     * Returns the locality where the mission took place
     * @return locality
     */
    public String getLocality() {
        return locality;
    }

    /**
     * Sets the locality where the mission took place
     * @param locality
     */
    public void setLocality(String locality) {
        this.locality = locality;
    }

    /**
     * Returns if this mission is repay or not
     * @return
     */
    public boolean isRepay() {
        return isRepay;
    }

    /**
     * Sets the boolean value if this mission is repay or not
     * @param isRepay
     */
    public void setRepay(boolean isRepay) {
        this.isRepay = isRepay;
    }
}

