package database;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.TypeConverters;
import android.arch.persistence.room.PrimaryKey;

/**
 * Represents one person that does some missions
 * @author Marco Olivieri on 26/11/2017 (Team 3)
 */

@Entity(tableName = Constants.PERSON_TABLE_NAME) @TypeConverters(Converters.class)

public class Person {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = Constants.PERSON_PRIMARY_KEY_NAME)
    private int ID;
    private String name;
    private String lastName;
    private String academicTitle;

    @Ignore
    /**
     * Non parametric constructor
     */
    public Person() {
    }

    /**
     * Parametric constructor
     *
     * @param name Name of the person
     * @param lastName Last Name of the person
     * @param academicTitle Academic Title of the person
     */
    public Person(String name, String lastName, String academicTitle) {
        this.name = name;
        this.lastName = lastName;
        this.academicTitle = academicTitle;
    }

    /**
     * Returns the Person ID
     * @return ID
     */
    public int getID() {
        return ID;
    }

    @Deprecated
    /** This method should no longer exists, since the ID is auto-generated by the database
     * Sets person id
     * @param ID not null
     */
    public void setID(int ID) {
        this.ID = ID;
    }

    /**
     * Returns person's name
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets person's name
     * @param name not null
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns person's last name
     * @return lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets person's last name
     * @param lastName not null
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Returns person's academic title
     * @return academicTitle
     */
    public String getAcademicTitle() {
        return academicTitle;
    }

    /**
     * Sets person's academic title
     * @param academicTitle not null
     */
    public void setAcademicTitle(String academicTitle) {
        this.academicTitle = academicTitle;
    }

    //TODO override toString
}
