package database;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;
import android.net.Uri;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Created by Federico Taschin on 08/11/2017.
 */

//Entity class of Ticket. Should not be used outside of the database module.

@Entity
public class TicketEntity {

    @PrimaryKey(autoGenerate = true)
    private int ID;     //id univoco del ticket
    private Uri fileUri;    //percorso di salvataggio associato
    private BigDecimal amount;  //importo totale
    private String shop;    //nome del negozio
    private Date date;  //data del ticket
    private String title;   //titolo dato al ticket

    public TicketEntity() {
    }

    public TicketEntity(int id, Uri fileUri, BigDecimal amount, String shop, Date date, String title) {
        this.ID = id;
        this.amount = amount;
        this.date = date;
        this.fileUri = fileUri;
        this.shop = shop;
        this.title = title;
    }

    /**
     * Returns the ticket ID
     * @return  ID
     */
    public int getID() { return ID; }

    @Deprecated
    /** This method should no longer exists, since the ID is auto-generated by the database
     * Set ticket id
     * @param ID not null
     */
    public void setID(int ID) { this.ID = ID; }

    /**
     * Returns the date of the issue of the ticket
     *
     * @return date
     */
    public  Date getDate() { return date; }

    /**
     * Sets ticket date
     * @param date not null
     */
    public void setDate(Date date) { this.date = date; }

    /**
     * Returns ticket amount
     * @return amount
     */
    public  BigDecimal getAmount() { return amount; }

    /**
     * Sets ticket amount
     * @param amount not null
     */
    public void setAmount(BigDecimal amount) { this.amount = amount; }

    /**
     * Returns ticket file path
     * @return fileUri
     */
    public Uri getFileUri() { return fileUri; }

    /**
     * Sets ticket file path
     * @param fileUri not null
     */
    public void setFileUri(Uri fileUri) { this.fileUri = fileUri; }

    /**
     * Returns the shop
     * @return shop
     */
    public String getShop() { return shop; }

    /**
     *
     * @param shop not null
     */
    public void setShop (String shop) { this.shop = shop; }

    /**
     * Restituisce il titolo del Ticket
     *
     * @return title
     */
    public String getTitle() { return title; }

    /**
     * Imposta il titolo del Ticket
     *
     * @param title not null
     */
    public void setTitle (String title) { this.title = title; }

    /**
     * Returns a String with Ticket data formatted as follows:
     * "Shop"
     * Totale: "Amount"
     *
     * @return string
     */
    @Override
    public String toString(){
        return getShop()+"\nTotale: "+getAmount();
    }
}
