package database;

import java.util.Date;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.TypeConverters;
import android.arch.persistence.room.PrimaryKey;
import android.net.Uri;

/**
 * Represents one mission and its associated information
 * @author Marco Olivieri(Team 3)
 */


@Entity(tableName = Constants.MISSION_TABLE_NAME,
        foreignKeys = @ForeignKey(entity = PersonEntity.class,
                parentColumns = Constants.PERSON_PRIMARY_KEY,
                childColumns = Constants.PERSON_CHILD_COLUMNS,
                onDelete = ForeignKey.CASCADE))
@TypeConverters(Converters.class) // automatic converters for database correct type

public class MissionEntity {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = Constants.MISSION_PRIMARY_KEY)
    private long ID;
    private Date startDate;
    private Date endDate;
    private String location;

    @ColumnInfo(name = Constants.MISSION_FIELD_REPAID)
    private boolean isRepay=false;
    private Uri excel;
    private String name;

    @ColumnInfo(name = Constants.PERSON_CHILD_COLUMNS)
    private int personID;

    @Ignore
    /**
     * Non parametric constructor to use when you don't want set all fields
     */
    public MissionEntity() {
    }

    /**
     * Parametric constructor
     *
     * @param startDate Date of the beginning of the mission
     * @param endDate Date of the end of the mission
     * @param location Name of location where the mission took place
     * @param personID code of the person of this mission
     */
    public MissionEntity(String name, Date startDate, Date endDate, String location, int personID) {
        this.startDate = startDate;
        this.endDate = endDate;
        this.location = location;
        isRepay = false;
        excel = null;
        this.personID = personID;
        this.name = name;
    }

    /**
     * Returns the mission ID
     * @return  ID
     */
    public long getID() {
        return ID;
    }

    @Deprecated
    /** This method should no longer exists, since the ID is auto-generated by the database
     * Set mission id
     * @param ID not null
     */
    public void setID(long ID) {
        this.ID = ID;
    }

    /**
     * Returns the beginning date of the mission
     * @return startDate
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * Sets the beginning date of the mission
     * @param startDate
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the end date of the mission
     * @return endDate
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * Sets the end date of the mission
     * @param endDate
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * Returns the location where the mission took place
     * @return location
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the location where the mission took place
     * @param location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Returns if this mission is repay or not
     * @return
     */
    public boolean isRepay() {
        return isRepay;
    }

    /**
     * Sets the boolean value if this mission is repay or not
     * @param isRepay
     */
    public void setRepay(boolean isRepay) {
        this.isRepay = isRepay;
    }

    /**
     * Returns path of the file excel format
     * @return excel
     */
    public Uri getExcel() {
        return excel;
    }

    /**
     * Sets path of the file excel format
     * @param excel
     */
    public void setExcel(Uri excel) {
        this.excel = excel;
    }

    /**
     * Returns person id of this mission
     * @return personID
     */
    public int getPersonID() {
        return personID;
    }

    /**
     * Sets person id of this mission
     * @param personID
     */
    public void setPersonID(int personID) {
        this.personID = personID;
    }

    /**
     * Returns the name of this mission
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of this mission
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

}

