package database;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.TypeConverters;
import android.arch.persistence.room.PrimaryKey;
import android.arch.persistence.room.ColumnInfo;
import android.net.Uri;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;


/**
 * Represents the ticket and its associated information
 * @author Marco Olivieri (Team 3)
 */

@Entity(tableName = Constants.TICKET_TABLE_NAME,
        foreignKeys = @ForeignKey(entity = MissionEntity.class,
                parentColumns = Constants.MISSION_PRIMARY_KEY,
                childColumns = Constants.MISSION_CHILD_COLUMNS))
@TypeConverters(Converters.class) // automatic converters for database correct type

public class TicketEntity {

    @ColumnInfo(name = Constants.TICKET_PRIMARY_KEY)
    @PrimaryKey(autoGenerate = true)
    private long ID;
    private Uri fileUri;
    private BigDecimal amountTicket;    //the total amount in the ticket
    private String shop="";
    private Date date;
    private String title="";
    private List<String> category;
    private float[] corners;
    private Date insertionDate;
    private short tagPlaces;    //the number of place setting in the ticket
    private BigDecimal pricePerson; //the single total for person (amountTicket/tagPlaces)

    @ColumnInfo(name = Constants.MISSION_CHILD_COLUMNS)
    private int missionID;

    @Ignore
    /**
     * Non parametric constructor to use when you don't want set all fields
     */
    public TicketEntity() {
        tagPlaces = 1;
    }

    /**
     * Parametric constructor
     *
     * @param fileUri Path associated with the the ticket file stored in the memory
     * @param amountTicket total amountTicket
     * @param shop Name of the shop in which the ticket was issued
     * @param date the issue date of the ticket
     * @param title name given
     * @param missionID code of the mission
     */
    public TicketEntity(Uri fileUri, BigDecimal amountTicket, String shop, Date date, String title, int missionID, short tagPlaces) {
        this.amountTicket = amountTicket;
        this.date = date;
        this.fileUri = fileUri;
        this.shop = shop;
        this.title = title;
        this.missionID = missionID;
        corners = new float[8];
        this.tagPlaces = tagPlaces;
    }

    /**
     * Returns the ticket ID
     * @return  ID
     */
    public long getID() {
        return ID; }

    @Deprecated
    /** This method should no longer exists, since the ID is auto-generated by the database
     * Set ticket id
     * @param ID not null
     */
    public void setID(long ID) { this.ID = ID; }

    /** Created by Marco Olivieri
     * Returns the date of the issue of the ticket
     *
     * @return date
     */
    public  Date getDate() { return date; }

    /** Created by Marco Olivieri
     * Sets ticket date
     * @param date not null
     */
    public void setDate(Date date) { this.date = date; }

    /** Created by Marco Olivieri
     * Returns ticket amount
     * @return amountTicket
     */
    public  BigDecimal getAmountTicket() { return amountTicket; }

    /** Created by Marco Olivieri
     * Sets ticket amount
     * @param amountTicket not null
     */
    public void setAmountTicket(BigDecimal amountTicket) {
        this.amountTicket = amountTicket;
    }

    /** Created by Marco Olivieri
     * Returns ticket file path
     * @return fileUri
     */
    public Uri getFileUri() { return fileUri; }

    /** Created by Marco Olivieri
     * Sets ticket file path
     * @param fileUri not null
     */
    public void setFileUri(Uri fileUri) { this.fileUri = fileUri; }

    /** Created by Marco Olivieri
     * Returns the shop
     * @return shop
     */
    public String getShop() { return shop; }

    /** Created by Marco Olivieri
     * Sets ticket shop
     * @param shop not null
     */
    public void setShop (String shop) { this.shop = shop; }

    /** Created by Marco Olivieri
     * Returns the title of the ticket
     *
     * @return title
     */
    public String getTitle() { return title; }

    /** Created by Marco Olivieri
     * Sets the title of the ticket
     *
     * @param title not null
     */
    public void setTitle (String title) { this.title = title; }

    /** Created by Marco Olivieri
     * Returns the list of categories of the ticket
     *
     * @return category
     */
    public List<String> getCategory() { return category; }

    /** Created by Marco Olivieri
     * Sets the list of categories of the ticket
     * @param categories
     */
    public void setCategory(List<String> categories) {
        this.category = categories;
    }

    /** Created by Marco Olivieri
     * Returns the mission id of this ticket
     * @return missionID
     */
    public int getMissionID() {
        return missionID;
    }

    /** Created by Marco Olivieri
     * Sets mission id of this TicketEntity
     * @param missionID
     */
    public void setMissionID(int missionID) {
        this.missionID = missionID;
    }


    /** Created by Marco Olivieri
     * Returns the corners of the ticket
     * 8 float point of the rectangle coordinate
     * @return corners
     */
    public float[] getCorners() {
        return corners;
    }

    /** Created by Marco Olivieri
     * Sets corners of the ticket
     * Must be an array of 8 elements: the rectangle coordinate of the ticket
     * @param corners
     */
    public void setCorners(float[] corners) {
        this.corners = corners;
    }

    /**Created by Federico Taschin
     * @return insertion date (not null) of the ticket
     */
    public Date getInsertionDate() {
        return insertionDate;
    }

    /**Created by Federico Taschin
     *
     * @param insertionDate
     */
    public void setInsertionDate(Date insertionDate) {
        this.insertionDate = insertionDate;
    }

    /** Created by Marco Olivieri
     * Returns the numer of place setting of the ticket.
     * If return 0 this ticket must not to be in the final repayment
     * @return the numer of place setting
     */
    public short getTagPlaces() {
        return tagPlaces;
    }

    /** Created by Marco Olivieri
     * Sets the numer of place setting of the ticket.
     * This number had not to be negative.
     * If tagPlaces is 0 it's means this ticket must not to be in the final repayment.
     * @param tagPlaces not negative
     */
    public void setTagPlaces(short tagPlaces) {
        this.tagPlaces = tagPlaces;

    }

    /** Created by Marco Olivieri
     * Returns the price of the single person
     * @return price Person
     */
    public BigDecimal getPricePerson() {
        if(tagPlaces == 1)
            pricePerson = amountTicket;
        else if(tagPlaces == 0)
            pricePerson = BigDecimal.ZERO;
        else if(tagPlaces > 1 && amountTicket != null) //divide amountTicket for the number of place setting
            pricePerson = amountTicket.divide(new BigDecimal(tagPlaces));
        return pricePerson;
    }

    @Deprecated
    /** This method should no exists, the single price if automatic set
     * Sets price Person
     * @param pricePerson not negative
     */
    public void setPricePerson(BigDecimal pricePerson) {
        this.pricePerson = pricePerson;
    }

    /**
     * Returns a String with TicketEntity data formatted as follows:
     * "Shop"
     * Totale: "Amount"
     *
     * @return string
     */
    @Override
    public String toString(){
        return getShop()+"\nTotale: "+ getAmountTicket();
    }

}